### ISSUE TITLE
Docker container fails to start with latest image

### ISSUE THREAD

**Issue by ghost** [techno-express/MeshCentral2#1]
I first tested out your Docker image yesterday and everything worked fine. The latest commit at the time was [this one](https://github.com/techno-express/MeshCentral2/commit/2c762e5c500393a206392772a70c250bbd4c314d). Today I pulled the latest MeshCentral Docker image and received the following error message after trying to run it:

```
Starting meshcentral ... error

ERROR: for meshcentral  Cannot start service meshcentral: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/home/meshserver/meshcentral-data/startmeshcentral.sh\": stat /home/meshserver/meshcentral-data/startmeshcentral.sh: no such file or directory": unknown

ERROR: Encountered errors while bringing up the project.
```

I suspect that this error is related to the change you made in [this commit](https://github.com/techno-express/MeshCentral2/commit/84ed34c317e32f2bf9cc0b0f0be7739c21acfb17).

**Edit:** I think the reason why that commit broke things is because the folder that you moved the startmeshcentral.sh file to is one of the folders that is mapped to a folder on the host file system where this file does not exist. I recommend reverting the first part of the commit to fix this issue.

**Edit 2:** A temporary workaround is downloading the startmeshcentral.sh file from GitHub, placing it in the mapped folder on the host file system and giving it execution permissions for the root user.

**Edit 3:** I opened PR #2 to fix this issue.

**Comment by ghost** [comment]
@techno-express What are your thoughts on this issue?

**Comment by TheTechsTech** [comment]
Have you tried deleting old image volumes created also? 
When you rebuild with last commit, the changes will not be put, changes won't be applied to volumes. I had same problem also. I deleted anything.

The reason for that last commit change was make things simpler for reconfiguration setup access on restart and shutdowns. The old way i had no direct access to the file, it's in the image, not data volumes, had to go thru hoops, SSH.

**Comment by ghost** [comment]
@techno-express Yeah, I've deleted all old image volumes. I assume the "workaround" I mentioned in my issue is how it's supposed to work?

**Comment by TheTechsTech** [comment]
The workaround is what the build image is suppose to do. Not sure why you getting this error.

What is you Docker run commands? Or how are you starting the image?

**Comment by ghost** [comment]
@techno-express I was getting the error because the file wasn't present in the mapped folder. Once I downloaded the file from the repository and placed it in said folder, the error disappeared. It wasn't clear to me that that was what you needed to do from the Docker image description, but I guess I can close this issue now.

**Comment by TheTechsTech** [comment]
OK, if your are creating the docker file, yes, the file needs to be in mapped folder. Which i am now figuring what has happened for you to have gotten the error.
But, if you are using the Docker run commands and pulling as posted, no, you shouldn't had to do that for it to work.
